alias ytvw='clear; youtube-viewer'
alias ytjb='clear; youtube-viewer -n'
alias pdfauto='ls *.tex | entr pdflatex --interaction=nonstopmode'
alias pdflatexq='pdflatex --interaction=nonstopmode'
alias mount-user='mount -o umask=0077,gid=1000,uid=1000'
alias xclip-ib='xclip -i -selection clipboard'
alias xclip-ob='xclip -o -selection clipboard'
