#!/bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=20
PANEL_FONT_0=

clock(){
    date +%H:%M
}

calender(){
    date +%F
}

battery(){
    cat /sys/class/power_supply/BAT0/capacity
}

while :; do
    BAR_INPUT="${c}Life: $(battery)% Date: $(calender) Time: $(clock)"
    echo $BAR_INPUT
    sleep 5
done
