#! /bin/sh

sxhkd &

bspc monitor eDP1 -d '' '' '' '' '' '' '' ''
#bspc monitor HDMI1 -s eDP1

$HOME/.config/polybar/launch.sh &

bspc config border_width         1
bspc config window_gap           4
bspc config top_padding         24
bspc config bottom_padding       0
bspc config right_padding        0
bspc config left_padding         0
bspc config normal_border_color  '#1c2023'
bspc config focused_border_color '#95c7ae'

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#bspc config bottom_monocle_padding $(bspc config window_gap)
#bspc config left_monocle_padding $(bspc config window_gap)
#bspc config right_monocle_padding $(bspc config window_gap)

bspc rule -a neomutt desktop='^4'
bspc rule -a Signal desktop='^8'
bspc rule -a Discord desktop='^8'
bspc rule -a zoom desktop="^7"
bspc rule -a Zathura state=tiled

# bspc rule -a Polybar manage=off

xmodmap ~/.Xmodmap
xset b off
xsetroot -cursor_name left_ptr

pkill megasync; megasync &
pkill dunst; dunst &
pkill xcompmgr; xcompmgr &

pulseaudio --start
calcurse --daemon

# feh --randomize --bg-fill ~/Pictures/Wallpapers/Landscapes/*
set-wallpaper

# places polybar instance below the bspwm windows but above bspwm root
if [ -z "$(ifinstalled xdo)" ]; then

	xdo lower -N "Polybar"
	xdo above -N "Polybar" -t $(xdo id -N Bspwm -n root)

fi

# have to put this here to prevent extra top padding around polybar
bspc config top_padding         24
