#! /bin/sh

sxhkd &
xmodmap ~/.Xmodmap
xset b off
$HOME/.config/polybar/launch.sh &
pkill megasync; megasync &
pkill dunst; dunst &
pkill xcompmgr; xcompmgr &
pulseaudio --start
calcurse --daemon

feh --randomize --bg-fill ~/Pictures/Wallpapers/Landscapes/*

bspc monitor -d '' '' '' '' '' '' '' '' IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
